// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/wailsapp/wails/v3/pkg/application"
	"taie/internal/app"
	"taie/internal/data"
	"taie/internal/services"
)

// Injectors from wire.go:

// InitializeApp is the Wire injector. It is compiled only when running the
// `wire` tool (build tag `wireinject`); the generated implementation lives in
// wire_gen.go. Regenerate with `make wire` (or the `wire` CLI) after changing
// providers.
func InitializeApp() (*application.App, error) {
	fs := _wireFSValue
	string2 := _wireStringValue
	dataData, err := data.NewData(string2)
	if err != nil {
		return nil, err
	}
	modelRepo := data.NewModelRepo(dataData)
	modelServices := services.NewModelServices(modelRepo)
	agentServices := services.NewAgentServices(modelRepo)
	applicationApp := app.NewWailsApp(fs, modelServices, agentServices)
	return applicationApp, nil
}

var (
	_wireFSValue     = assets
	_wireStringValue = data.DefaultDSN
)
