// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as po$0 from "../po/models.js";

/**
 * ModelList 是 List 的分页查询结果。
 */
export interface ModelList {
    "items": (po$0.AIModel | null)[] | null;
    "total": number;
}
