// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as po$0 from "../po/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create 新增一条模型记录
 */
export function Create(model: po$0.AIModel | null): $CancellablePromise<void> {
    return $Call.ByID(1710774176, model);
}

/**
 * Delete 按主键软删除模型记录
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(1824220191, id);
}

/**
 * GetByID 按主键查询单条模型记录
 */
export function GetByID(id: number): $CancellablePromise<po$0.AIModel | null> {
    return $Call.ByID(2660421896, id);
}

/**
 * List 按名字模糊搜索分页查询模型列表，name 为空时查全部
 */
export function List(name: string, page: number, pageSize: number): $CancellablePromise<$models.ModelList | null> {
    return $Call.ByID(4164338812, name, page, pageSize);
}

/**
 * Update 保存模型的所有字段
 */
export function Update(model: po$0.AIModel | null): $CancellablePromise<void> {
    return $Call.ByID(266569269, model);
}
