// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as po$0 from "../po/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete 按主键软删除会话记录。内存中缓存的 agent 由 ChatAgent 的空闲淘汰
 * 自行回收（陈旧 entry 不再被命中，空闲超时后被清理）。
 */
export function Delete(req: $models.DeleteSessionReq | null): $CancellablePromise<void> {
    return $Call.ByID(724597624, req);
}

export function GetMessage(req: $models.ChatSessionReq | null): $CancellablePromise<(po$0.ChatMessage | null)[] | null> {
    return $Call.ByID(3263160644, req);
}

/**
 * List 按标题模糊搜索分页查询会话列表，title 为空时查全部
 */
export function List(req: $models.ListSessionReq | null): $CancellablePromise<$models.SessionList | null> {
    return $Call.ByID(900932819, req);
}
