// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as po$0 from "../po/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Get 返回系统设置
 */
export function Get(): $CancellablePromise<po$0.SystemConfig | null> {
    return $Call.ByID(947393774);
}

/**
 * Update 整体覆盖写回系统设置
 */
export function Update(req: $models.UpdateSystemReq | null): $CancellablePromise<void> {
    return $Call.ByID(2654166619, req);
}
