// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DailyUsage 按天聚合 token 用量；限定了天数时把区间内没有用量的日期补 0，保证图表 x 轴连续
 */
export function DailyUsage(req: $models.TokenUsageReq | null): $CancellablePromise<($models.TokenDailyStat | null)[] | null> {
    return $Call.ByID(3438064097, req);
}

/**
 * ModelUsage 按模型名称聚合 token 用量
 */
export function ModelUsage(req: $models.TokenUsageReq | null): $CancellablePromise<($models.TokenModelStat | null)[] | null> {
    return $Call.ByID(2606885645, req);
}

/**
 * SessionUsage 按会话聚合 token 用量
 */
export function SessionUsage(req: $models.TokenUsageReq | null): $CancellablePromise<($models.TokenSessionStat | null)[] | null> {
    return $Call.ByID(4259221598, req);
}
