// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * EnableTools 启用/禁用工具；启用前要求已配置参数
 */
export function EnableTools(req: $models.EnableReq | null): $CancellablePromise<void> {
    return $Call.ByID(1581005616, req);
}

/**
 * List 分页返回工具配置
 */
export function List(req: $models.ListToolReq | null): $CancellablePromise<$models.ToolList | null> {
    return $Call.ByID(3966881454, req);
}

/**
 * Update 只更新工具的配置参数，其余字段原样保留
 */
export function Update(req: $models.UpdateToolReq | null): $CancellablePromise<void> {
    return $Call.ByID(2291170411, req);
}
