// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AIModel maps to the ai_model table defined in migrations/create_ai_model.sql.
 */
export interface AIModel {
    "id": number;
    "created_at": string;
    "updated_at": string;

    /**
     * 模型名称
     */
    "name": string;

    /**
     * 模型 API Key
     */
    "key": string;

    /**
     * 模型服务地址
     */
    "base_url": string;

    /**
     * 模型类型
     */
    "type": number;

    /**
     * 模型提供方
     */
    "provider": string;

    /**
     * 是否启用 0-禁用 1-启用
     */
    "enable": number;
}
