// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../../gorm.io/gorm/models.js";

/**
 * AIModel maps to the ai_model table defined in migrations/create_ai_model.sql.
 */
export interface AIModel {
    "id": number;
    "createdAt": string;
    "updatedAt": string;

    /**
     * 模型名称
     */
    "modelName": string;

    /**
     * 模型 API Key
     */
    "apiKey": string;

    /**
     * 模型服务地址
     */
    "baseUrl": string;

    /**
     * 模型类型
     */
    "type": number;

    /**
     * 模型提供方
     */
    "provider": string;

    /**
     * 是否启用 0-禁用 1-启用
     */
    "enable": number;
}

export interface ChatMessage {
    /**
     * through Model
     */
    "ID": number;

    /**
     * through Model
     */
    "CreatedAt": string;

    /**
     * through Model
     */
    "UpdatedAt": string;

    /**
     * through Model
     */
    "DeletedAt": gorm$0.DeletedAt;
    "SessionID": number;
    "Role": string;
    "Content": string;
    "MultiContent": string | null;
    "ToolCalls": string | null;
    "ToolCallID": string;
    "Name": string;
    "Extra": string | null;
}

export interface ChatSession {
    "id": number;
    "createdAt": string;
    "updatedAt": string;
    "title": string;
    "systemPrompt": string;

    /**
     * 模型名称
     */
    "modelName": string;

    /**
     * 模型 API Key
     */
    "apiKey": string;

    /**
     * 模型服务地址
     */
    "baseUrl": string;
    "meta": string | null;
    "endedAt": string | null;
}

export interface CommonJson {
    /**
     * 字段名，作为表单的 key
     */
    "label": string;

    /**
     * 展示名，表单 label 显示用
     */
    "name": string;
    "value": string;
}

/**
 * NotificationSetting 各类事件的通知开关。
 */
export interface NotificationSetting {
    /**
     * 响应补全完成时通知
     */
    "responseCompletions": boolean;

    /**
     * 计划任务执行时通知
     */
    "scheduledTasks": boolean;

    /**
     * 事件通知
     */
    "notifications": boolean;

    /**
     * 需要授权时通知
     */
    "permissionRequests": boolean;

    /**
     * 云会话邮件
     */
    "emails": boolean;
}

/**
 * PermissionSetting agent 内置工具的授权开关，key 与工具名一一对应。
 */
export interface PermissionSetting {
    /**
     * read_file：读取文件内容
     */
    "read_file": boolean;

    /**
     * write_file：写入文件内容
     */
    "write_file": boolean;

    /**
     * edit_file：编辑文件内容
     */
    "edit_file": boolean;

    /**
     * glob：根据 glob 模式查找文件
     */
    "glob": boolean;

    /**
     * grep：在文件中搜索内容
     */
    "grep": boolean;

    /**
     * execute：执行 shell 命令
     */
    "execute": boolean;
}

/**
 * SystemConfig 是 .conf/system.json 中的应用系统设置（语言、工作模式、通知与文件权限开关）。
 */
export interface SystemConfig {
    /**
     * agent 回答使用的语言，如 zh-CN / en
     */
    "language": string;

    /**
     * 工作模式：manual 手动 / plan 计划 / auto 自动（减少询问）
     */
    "mode": string;

    /**
     * 界面字号
     */
    "fontSize": string;
    "notifications": NotificationSetting;
    "permissions": PermissionSetting;
}

/**
 * ToolConfig 是 .conf/tools.json 数组中的一个工具配置（所有工具集中在这一个文件里）。
 */
export interface ToolConfig {
    "toolName": string;
    "desc": string;
    "info": string;

    /**
     * 配置参数
     */
    "args": CommonJson[] | null;
    "enable": boolean;
}
